iraf-community/pyraf

setup.cfg
Change the packages attr in setup.cfg to add `old_files` dir, and add the ``__init__.py`` file (empty).
=> make "old_files" dir importable in pyraf

lib/pyraf/old_files/subproc_tests.py
This test is failing bc Subprocess.wait() returns an int, but we are checking for True (via `is`).  Not really sure how this was ever passing before, unless perhaps Py27 was casting that for us without our knowledge.
I have confirmed manually that the new code does The Right Thing here.  It should only throw the assert if `wait()` returns 0.
=> fix to subproc_tests.test() to not use "is" so casually

tests/test_core_nongraphics.py
=> TST: Fix subproc wait test

Jenkinsfile
The CI utilities library that Jenkins uses to provide the convenience syntax used in the Jenkinsfile has been updated to temporarily honor both .build_mode and .name as a step towards transitioning to the new property .name for clarity. Once all projects using the CI utilities are updated, support for the old .build_mode name will be removed.
=> Change 'build_mode' to 'name' to reflect CI utils update.

lib/pyraf/GkiMpl.py, lib/pyraf/MplCanvasAdapter.py
The `FigureCanvasApp.show()` in matplotlib command was replaced by `draw()` in matplotlib-3.0 (2018).
Also, there was a deprecation of the `resize_event` parameter in the `FigureCanvasApp` constructor, which was deprecated in matplotlib-3.4 (2021).
Fixes: #72 
@jrthorstensen Could you make a test with this change and tell whether it works?
=> Replace removed MplCanvasAdapter.show() with ..draw()

defsetup.py, lib/pyraf/wutil.py
There were two links to www.stsci.edu left, which both don't work anymore. The link to the homepage is now changes to iraf-commuity, and the link to the FAQ is removed completely.
It may be a challenging TODO to dig out the original FAQ (the only one I found is a PDF).
=> Remove remaining www.stsci.edu links

pyraf/ipython_api.py, setup.cfg, setup.py
These versions are not used at Python 3 anyway, so we can remove the old code.
=> Remove support of ancient ipython versions

setup.py
On MacOS, the graphics works without X11; therefore the `xutil` module is not required there (instead `aqutil` is used). While the build *could* work there, it requires the installation of XQuartz (or similar), which is quite a heavy dependency.
To enable a simple installation on Macs, we therefore disable the build of the `xutil` extension.
=> Don't install xutil on MacOS

pyraf/gki.py
This is [deprecated in numpy 1.20](https://numpy.org/devdocs/release/1.20.0-notes.html#using-the-aliases-of-builtin-types-like-np-int-is-deprecated) and shall be replaced with the standard int.
=> Remove numpy.int

pyraf/tests/test_plot.py
Currently, we check for the existence of the DISPLAY variable, which not really works f.e. on a Mac. This is now improved by trying a simple Tk init and destroy. See also [this StackOverflow discussion](https://stackoverflow.com/questions/69043362/how-do-i-find-out-in-python-whether-a-gui-is-available).
=> Improve check for the existence of a GUI

CODE_OF_CONDUCT.md, pyraf/cl2py.py, pyraf/cllinecache.py, pyraf/generic.py, pyraf/gki.py, pyraf/ipython_api.py, pyraf/irafecl.py, pyraf/irafexecute.py, pyraf/iraffunctions.py, pyraf/irafhelp.py, pyraf/irafimport.py, pyraf/irafnames.py, pyraf/irafpar.py, pyraf/iraftask.py, pyraf/tests/test_cli.py, pyraf/tests/test_core_nongraphics.py, pyraf/tests/test_plot.py, pyraf/tests/test_tasks.py
The main commit here changes all remaining internal pyraf imports into relative ones, despite of having them marked as "cyclic". This is not a real problem...
Also, remove the SystemExit() raises within the package -- they will unexpectedly end an interactive session on (some) errors.
Finally, the stacksize problem on LInux is fixed since a long time, so we can remove this as well.
Oh, and some more STScI references are going away.... (including the Code of Conduct, see #88)
=> Consequently use relative imports within the package (and more...)

pyraf/wutil.py
This way tkinter is not required to run pyraf in headless mode. For example, on Debian/Ubuntu tkinter is an extra package, "python3-tk" which would not needed for a script-only processing.
=> Import tkinter in wutil only when required

pyraf/irafecl.py, pyraf/tests/test_cli.py, pyraf/tests/test_invocation.py
There was a separate place for division in ECL mode (due to an extended error handling in this case). This place needed to be    extended to handle integer/integer division.
This chance is then taken to run some tests also in ecl mode.
=> Fix integer division with Python 3 in ecl mode

pyraf/clcache.py, pyraf/iraffunctions.py, pyraf/sqliteshelve.py, pyraf/tests/test_cli.py
This simplifies the code and makes the behavior more predictable, as it is clear that only the first entry will be used for writing.
Also this gives the opportunity to have an internal dictionary as a fallback cache. This speeds up the computation a bit. Also the cache tables for code with and without ECL are combined into one. This simplifies the internal handling (as the check for the version at the opening is not needed anymore) and the user does not have to deal with different files for use with and without ECL.
The environment variable that can change the default cache paths is `PYRAF_CLCACHE_PATH`. Setting it do `disable` will disable the cache, and rely on the internal fallback.
Some bugs found in this process are also fixed.
=> Explicitly use the first cache for writing in clcache.py

.github/workflows/citest.yml, README.rst, pyraf/__main__.py, pyraf/epar.py, pyraf/iraffunctions.py
This PR collects various small bug fixes found during testing.
* another Tkinter leftover, this was forgotten during the py2->py3 transition, and is required for the graphical parameter editor.
* restore default (commandwrapper) mode for pyraf script,
* add necessary imports in `__main__.py`
* Re-introduce stack limit unsetting on old Linux systems.
Fixes: #99
=> Various small bugfixes

.github/workflows/citest.yml, MANIFEST.in, pyraf/irafhelp.py, setup.cfg
This includes
* metadata
* Python version
For the Python version: we depend on stsci.tools >= 4.0.1, which by itself has a minimal Python version 3.6. So we can set this as well.
Fixes: #88
=> Update setup.cfg and other metadata

pyraf/tests/test_tasks.py
IRAF 2.17 remove the "mkmanpage" command, so we can't use it as a command to test PyRAF.
=> Replace removed mkmanpage package test with mkhelpdb test

pyraf/tests/test_invocation.py
This reorders the asserts a bit so that first the result code from the invocation is checked (and on error, stderr is returned), and then the output is checked. This has the advantage that we may see why the invocation failed instead of just seeing that stdout was empty. 
It is mysterious however why sometimes the invocation fails (as seen on [Ubuntu, armhf](https://autopkgtest.ubuntu.com/results/autopkgtest-jammy/jammy/armhf/p/pyraf/20220115_091433_e8d28@/log.gz)).
=> First test for result code in test_invocation

pyraf/clscan.py, pyraf/tests/test_cli.py
=> Resolve CL syntax error when assigning value to array element on Py 3 (#115)

pyraf/tests/test_cli.py, pyraf/tests/test_invocation.py, pyraf/tests/test_using_tasks.py
This is a small cleanup PR, which came up from the discussion in https://github.com/iraf-community/pyraf/pull/116#issuecomment-1033782103
=> Remove unnecessary pytest tmpdir fixture

pyraf/irafhelp.py
[webbrowser](https://docs.python.org/3/library/webbrowser.html) is available since long and provides a standard conform access to a webbrowser.
HTML help still however does not work yet because the documentation is structured hierarchically on [readthedocs](https://iraf.readthedocs.io/en/latest/tasks/index.html), but the PyRAF help does not have the hierarchical path of the help target. Still unclear where to adjust this.
=> Use Python's "webbrowser" module instead of irafutils.launchBrowser

pyraf/iraffunctions.py, pyraf/iraftask.py
This gets rid of the temporary files that are written to `~/.iraf`, and often not (at least in my case) removed after processing.
The `IrafCLTask` class is slaready able to handle `StringIO` instead of files.
=> Use StringIO instead of temporary to handle non-persistent CL commands

pyraf/cl2py.py, pyraf/filecache.py, pyraf/graphcap.py, pyraf/irafecl.py, pyraf/irafexecute.py, pyraf/iraffunctions.py, pyraf/irafpar.py, pyraf/subproc.py, pyraf/tests/test_cli.py
IRAF is not able to handle non-ASCII chars (and will probably never do). We need to be robust here to not fail on files that have
non-ASCII characters, f.e. in comments.
Fixes: #117
Todo:
=> Handle non-ASCII Unicode and binary files on stdin/stdout/stderr

pyraf/iraffunctions.py, pyraf/tests/test_cli.py
Fixes one of the changes due to Python 3 in #127.
=> Make iraf.nint() on Py 3 round n+0.5 upwards like CL & Py 2

pyraf/irafcompleter.py
Taken from https://github.com/iraf-community/pyraf/issues/127#issuecomment-1069686988:
In Python 3.4, tab completion stopped working directly after f.e. a completed directory name:
imhead /data/<tab>
just inserts a tabulator instead of listing all available files. The reason is the commit https://github.com/python/cpython/commit/aaf6114b37 which is aimed to fix [Python#23441](https://bugs.python.org/issue23441).
The problem described there (<tab> at an empty line) is not relevant for PyRAF, so we revert the change in the `IrafCompleter.complete()` method.
By chance, we also changed a variable name that was overwriting a builtin function (`dir`).
@jehturner Can you test if this works for you?
=> Fix tab completion for empty input

pyraf/tests/test_cli.py
Is this a good solution for #136? I realized after the fact that this patch may be unnecessarily general, because `stsdas` is the only optional package that can be loaded when running the tests, so `img` & `dis` should be the only 2 cases that will ever fail. However, it's still more robust against any future test cases being added that might only become ambiguous when `stsdas` is loaded (eg. something like `tt` would do it). Anyway, feel free to merge this or use your own fix.
Fixes: #136
Is there any chance of a release candidate that I could test in the relatively near future? :wink: Thanks!
=> Allow for `which` matching additional stsdas tasks to abbreviations

pyraf/tests/test_using_tasks.py
The input image was shrunk to save space in 3dfcd888 and the expected output values need updating in 2 tests to make them pass again when STSDAS is available. Closes #135.
=> Update msstat tests after the input image was reduced in size

pyraf/iraffunctions.py
AstroConda versions of macosx (32 bit) seem to have the same problem now, so we pragmatically use the workaround here as well.
See https://github.com/iraf-community/pyraf/issues/139#issuecomment-1083964636 and https://github.com/iraf-community/pyraf/issues/99#issuecomment-1083931403.
@jehturner, can you check this? If this works, I would move release date to early next week (unless there is another problem).
=> Set stacksize to unlimited for macosx as well

pyraf/clcache.py, pyraf/sqliteshelve.py
Protocol version 4 is supported since Python 3.4 and the default starting with Python 3.8.
Fixing the protocol version allows to downgrade the Python version. To make it more robust, also trigger a re-build of the cache entry if the cache was written by an unsupported protocol version.
Fixes #142.
=> Fix pickle protocol

pyraf/tools/editpar.py
Apparently using `update()` for tkinter objects hang the process when `epar` is executed in pyraf. Using `update_idletasks()` appears to fix it.
This is a possible fix for #144
I added `# isort: skip` to avoid auto-formatting with my editor (I couldn't disable it, sorry). Please ignore these changes.
=> Use `update_idletasks()` to avoid hangs on epar GUI window.

pyraf/iraffunctions.py
This will make PyRAF working again with a personal IRAF installation, where the `login.cl` is not in `/etc/iraf/`.
Closes: #149
=> Search login.cl in hlib$ as final resort

pyraf/MplCanvasAdapter.py
With the matplotlib backend, pyraf window becomes blank when resizing it.
I added `self.draw_idle()` to prevent it.
This is a hotfix of #157 and PR for #160
=> Fix blank window issue when resizing

setup.cfg
On macOS, there are three possible ways to create interactive graphics: aqua, x11, matplotlib. 
By default, this should probably be aqua, and aqua requires additionally the **pyobjc** package and its dependencies.
One question however is whether this should be *required*. This PR makes it required as a base for testing and discussion.
Cc @monodera 
This could fix #156
=> Require pyobjc on macOS

pyraf/aqutil.py
This just replaces **GetCurrentProcess()**, **GetFrontProcess()**, **SetFrontProcess()** and **CPSSetProcessName()** with their Cocoa counterparts. 
The undocumented function **CPSEnableForegroundOperation()** is removed as it seems that it is no longer needed.
Tested on an Intel Mac, Catalina 10.15.7 and Sonoma 14.4. @mjfitzpatrick could you test this on a Sonoma ARM Mac (`pip3 install git+https://github.com/iraf-community/pyraf@cocoa`)?
Fixes #163
=> Use Cocoa API for window activation/deactivation handling

pyraf/iraffunctions.py
These variables are now retrieved from the configuration for the different IRAF architectures instead of from `/usr/local/bin/cl`.
The problems here were that
* `/usr/local/bin/cl` does not necessarily exist (maybe `irafcl`, or at different locations)
* the structure of this file changed, there is no longer a unconditional **exec** statement at the end
Also, there are better ways to find out the iraf variable, which are all tested here:
* Community IRAF puts the IRAF path in `~/.iraf/irafroot` resp. `/etc/iraf/irafroot`,
* personal installations of NOAO and NOIRLab IRAF have an `export iraf=/..." statement in `~/.iraf/setup.sh`,
* system installation of NOAO IRAF uses a define in `/usr/include/iraf.h` for this,
* There a a number of pre-defined ways, like `/usr/lib/iraf/`, …
=> Update determination of iraf and IRAFARCH variables

pyraf/gki.py, pyraf/gkitkbase.py, pyraf/iraffunctions.py
This class was never used, and its only potential usage (commented out) was removed in 2008. So it is safe to completely erase it:
When following the use of **IrafHatchFills** in PyRAF, it looks that the only place is in the initialization of kiInteractiveTkBase: https://github.com/iraf-community/pyraf/blob/151350f040c0b7fb770c65d68c07b5979523ec6e/pyraf/gkitkbase.py#L205-L212
The attribute **hatchfills** is then never references within the PyRAF code base. The only reference I could find is in `gkiopengl.py`; however there it was always commented out (since its introduction before 2000): https://github.com/iraf-community/pyraf/blob/5f6f68df0a0f9e78f0717716ff9afc59f325a59f/lib/gkiopengl.py#L360-L371
This was however removed in 70b0404 2008.
**hatchfills** is also not part of a Tcl/Tk …
=> Remove IrafHatchFills
